import GroupCard from "../molecules/groupCard";

export default function GroupSearchSection () {
    return (
        <div className="p-8 w-full space-y-6 overflow-auto max-h-150">
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
            <GroupCard variant="search" image="https://media.istockphoto.com/id/1371940128/es/foto/amigos-multirraciales-tomando-selfies-de-grupos-grandes-sonriendo-a-la-cámara-jóvenes-que-se.jpg?s=612x612&w=0&k=20&c=a3RfD8AnfDIG-4mChU3DexLa_spWt4jzQMHUj8CGBtc=" title="Equipo 1" text="Tema: Tema del grupo" text2="594 miembros" button="Unirse"></GroupCard>
        </div>
    )
}